trigger:
  - master

strategy:
  matrix:
    linux:
      imageName: 'ubuntu-16.04'
    mac:
      imageName: 'macos-10.14'
    windows:
      imageName: 'vs2017-win2016'

pool:
  vmImage: $(imageName)

steps:

- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- bash: |
    /usr/bin/Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
    echo ">>> Started xvfb"
  displayName: Start xvfb
  condition: and(succeeded(), eq(variables['Agent.OS'], 'Linux'))

- bash: yarn && yarn lint && yarn test
  displayName: Command test
  env:
    DISPLAY: ':99.0'

- bash: yarn gen-keys
  displayName: Keybinding generator test

- bash: |
    npm install -g vsce
    vsce package
  displayName: Packaging test
