name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  tests:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout
      uses: actions/checkout@v2.3.5
    - name: Install Node.js
      uses: actions/setup-node@v2.4.1
      with:
        node-version: 16.x

    - name: Get yarn cache directory path
      id: yarn-cache-dir-path
      run: echo "::set-output name=dir::$(yarn cache dir)"
    - uses: actions/cache@v2.1.6
      id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
      with:
        path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-

    - name: Install dependencies
      run: yarn --frozen-lockfile

    - name: ESLint & Prettier
      run: |
        yarn check:eslint
        yarn check:prettier

    - name: Test keybinding generator
      run: |
        yarn test-gen-keys
        yarn gen-keys
        git diff --quiet || (echo "You have to run 'yarn gen-keys' and commit the updated package.json" && exit -1)

    - name: Test
      run: xvfb-run -a yarn test
      if: runner.os == 'Linux'
    - name: Test
      run: yarn test
      if: runner.os != 'Linux'

    - name: Test packaging
      run: |
        yarn run vsce package
